project:
  type: website
  output-dir : docs


website:
  title: "Harper Noteboom"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: "Full Text Analysis" 
        href: text-analysis.qmd
      - text: Data Viz
        menu:
          - text: "Bechdel Test"
            href: data-viz/bechdel-test.qmd
          - text: "National Parks"
            href: data-viz/national-parks.qmd
      - text: "Simulation"
        href: simulation.qmd
    
format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual

