project:
  type: website
  output-dir : docs


website:
  title: "Harper Noteboom"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Data Viz
        menu:
          - text: "Bechdel Test"
            href: data-viz/bechdel-test.qmd
          - text: "National Parks"
            href: data-viz/national-parks.qmd
          - text: "National Parks - Interactive"
            href: data-viz/national-park-interactive.qmd
          - text: "Simulation"
            href: data-viz/simulation.qmd
          - text: "Data Ethics"
            href: data-viz/ethics.qmd
          - text: "SQL Analysis"
            href: data-viz/Project_5.qmd
          - text: "Full Text Analysis" 
            href: data-viz/text-analysis.qmd
      - text: "Final Presentation"
        href: final_pres.qmd
      - text: "Articles"
        href: articles.qmd
format:
  html:
    theme: jolla
    css: styles.css
    toc: true
    page-layout: full
    

editor: visual

