---
title: "Ethics in Data Science" 
format: html
---

##### Case Study: Target's pregnancy predicting algorithm

Target is a retail corporation and one of the nation’s biggest department store chains. They offer a wide variety of goods from groceries, to clothing, to baby products. In 2012, an article in the New York Times titled "*How Companies Learn Your Secrets*" by Charles Duhigg exposed the company’s "pregnancy predictor" algorithm. The algorithm, created by statistician Andrew Pole, uses customers’ shopping habits to predict if they are pregnant, with the goal of targeting advertising to increase sales and build customer loyalty. By predicting whether an individual is pregnant, Target can advertise baby products to them before the child is born and influence their shopping habits. This algorithm took data from customers, often without their knowledge or consent, and used it to benefit the company without the consumer knowing what was going on

### Background

Andrew Pole was hired by Target to use his insights into consumer habits to increase Target’s sales. He was tasked with identifying the moments in consumers’ lives where they are undergoing great changes and so their shopping habits were also susceptible to change. One such period was the time around the birth of a child. Target wanted to reach new parents before other brands could, which led them to want to know if their customers were pregnant, even if they didn't want the brand to know.

Pole began by looking at baby shower registries, where pregnant people willingly disclosed their pregnancy. He observed how these people’s spending habits changed as they approached their due date. One of the trends he noticed was that many people began to buy lots of unscented lotion around the beginning of their second trimester and an increase in vitamins in their first trimester. Through all of this data, Pole developed a list of 25 products that allowed him to give each consumer a "pregnancy prediction" score, as well as an estimate of their due date. This would then allow Target to send the customer specialized ads for relevant products as they approached their due date. Target also used information about habit building to increase the variety of products that consumers would purchase.

Pole then applied this algorithm to every regular female shopper in the nation and produced a list of thousands of people who it found were most likely pregnant. While this is not illegal—Target says they comply with all federal and state laws—and it isn't a case of leaked or stolen data, this story still spurs ethical questions related to data collection and use. Some of the ethical concerns that this raises are: Who benefits from the use of this data and who suffers? Should it be possible for brands to predict sensitive health information? What should they be able to do with this information?

### Data Values and Principles Manifesto

The first item in the Data Values and Principles Manifesto states, "Use data to improve life for our users, customers, organizations, and communities." This raises the question of whose life is really improved by this algorithm. Target might claim that the algorithm can actually be beneficial to pregnant people. By providing them with advertisements and coupons it makes it easier for customers to get the products they need and even save money.

As described in the New York Times article, new parents are often overwhelmed and they no longer want to shop at different stores for different items. By advertising the diversity of Target's products, they made it easier for parents to get everything they need from one store.

In the article, "Target Knows You're Pregnant; Is This What Customers Really Want," Brian Cantor makes the argument that consumers like when ads are targeted toward their preferences and needs and that it makes shopping a better experience for them.

However, I don't think this is actually improving the lives of users. Advertising is one thing, but using data to predict sensitive information about someone under the guise of benefiting them is different. In reality, Target, as a corporation, benefits from this algorithm.

Additionally, while Target might claim that this information is purely for advertising purposes, when placed in the wrong hands, information about a person’s reproductive status can have detrimental effects on their life. In the book Predictive Analytics by Eric Siegel, he cites an online user who explained the scenario of a pregnant woman with a precarious job, struggling to get state disability—if this woman’s pregnancy was leaked, she could risk losing her benefits and her job.

Especially in a post-Roe v. Wade society, reproductive information is extremely sensitive and the pregnant person should have full control over who knows that information. While this data increases Target's profits and could benefit customers, it also has the potential to harm many people.

### What was the consent structure?

The data being used came from baby registries, purchase history, and customer profiles. Customers making baby registries willingly provided their status and due date, and customers in the store technically agreed to Target knowing their purchase history. However, the "participants" whose data was being used were not aware of exactly the applications of their data.

Customers that have Target accounts or loyalty cards accept certain terms and conditions that are usually long and hard to understand. Technically, this is customers giving their consent to their data being used. Customers were not aware that their data would be used to create a predictive model that could reveal sensitive health information.

This creates the question of: Can you provide informed consent for applications that are not yet foreseen? Target customers could never have known what their data would be used for, and it is virtually impossible to ever give consent for future applications that are unknown. To some extent, that’s a risk we take in the digital age. However, I think that even if participants have given "consent," companies should be prevented from manipulating that "consent" in ethically ambiguous ways.

### Were the data made publicly available?

The algorithm that Pole created and the data about individuals’ "pregnancy scores" has not become publicly available. In this case, it is crucial to the privacy, autonomy, and well-being of Target customers that this data remains non-public. However, it is important to keep in mind that "non-public" does not mean private. Target could be selling this data to other companies so it is impossible to know who actually has access to this data and. Additionally, there could be some benefit to making the algorithm or anonymous data public so that the data science community can check for bias and keep Target accountable for their actions.

### Who was measured? Are the representative of whom we want to generalize?

Another ethical concern in this case study is representation. The individuals measured were regular Target shoppers who used loyalty cards or credit cards. This is not representative of the whole population and is likely skewed by demographics like income, age, and race. We don't know specifics of who and what was collected—this makes it impossible to see what biases exist in the data and thus the algorithm.

We need more information on the types of people that were measured and what demographics were collected to know if they are representative of the population to which the algorithm was applied, or to the public as a whole.

In conclusion, Targets "pregnancy predictor" raises many ethical questions surrounding data use and corporations use of data to predict sensitive health information about their customers.

### Sources:

Duhigg, Charles. “How Companies Learn Your Secrets.” The New York Times Magazine, 16 Feb. 2012, www.nytimes.com/2012/02/19/magazine/shopping-habits.html.

Cantor, Brian. “Target Knows You're Pregnant; Is This What Customers Really Want?” Customer Contact Week Digital, www.customercontactweekdigital.com/customer-experience/articles/target-knows-you-re-pregnant-is-this-what-customer. Accessed 16 Apr. 2025.

Siegel, Eric. Predictive Analytics: The Power to Predict Who Will Click, Buy, Lie, or Die. Revised and Updated ed., Wiley, 2016.
