---
title: "National Park Species"
format: html
execute:
  echo: false
  warning: false
author: Harper Noteboom
published: 2025/02/19
---

```{r}
library(tidyverse)
```

```{r}
most_visited_nps_species_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2024/2024-10-08/most_visited_nps_species_data.csv', show_col_types = FALSE)

most_visited_nps_species_data |> 
  filter(ParkCode == "ROMO") |> 
  group_by(CategoryName) |> 
  summarize(count = n()) |> 
  filter(count > 50) |> 
  ggplot(aes(x = reorder(CategoryName, -count), y = count, fill = CategoryName)) + 
    geom_col() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))+
    labs(
      x = "Species Category", 
      y = "Number of species",
      title = "Categories of Species in Rocky Mountain National Park",
      fill = "Category"
    )

```

The figure above shows the number of individual species in different species categories present in Rocky Mountain National Park.

References:

Original Source: https://irma.nps.gov/NPSpecies/Search/SpeciesList TidyTuesday Source: https://github.com/rfordatascience/tidytuesday/blob/main/data/2024/2024-10-08/readme.md
